CREATE TABLE dbo.ChangeLog (
	ChangeId INT NOT NULL AUTO_INCREMENT,
	Folder VARCHAR2(256) NOT NULL,
	ScriptNumber SMALLINT NOT NULL,
	ScriptName VARCHAR2(512) NOT NULL,
	StartDate TIMESTAMP NOT NULL,
	CompleteDate TIMESTAMP NULL,
	AppliedBy VARCHAR2(128) NOT NULL,
	ScriptStatus TINYINT NOT NULL,
	ScriptOutput CLOB NOT NULL
);

ALTER TABLE dbo.ChangeLog ADD CONSTRAINT PK_ChangeLog PRIMARY KEY (ChangeId);

CREATE INDEX IX_ChangeLog ON dbo.ChangeLog (Folder, ScriptNumber)