CREATE TABLE dbo.ChangeLog (
	ChangeId INT NOT NULL AUTO_INCREMENT,
	Folder VARCHAR(256) NOT NULL,
	ScriptNumber SMALLINT NOT NULL,
	ScriptName VARCHAR(512) NOT NULL,
	StartDate DATETIME NOT NULL,
	CompleteDate DATETIME NULL,
	AppliedBy VARCHAR(128) NOT NULL,
	ScriptStatus TINYINT NOT NULL,
	ScriptOutput TEXT NOT NULL
);

ALTER TABLE dbo.ChangeLog ADD CONSTRAINT PK_ChangeLog PRIMARY KEY (ChangeId);

ALTER TABLE dbo.ChangeLog ADD UNIQUE INDEX(Folder, ScriptNumber);