CREATE TABLE TABLE_NAME (
	ChangeId INT NOT NULL AUTO_INCREMENT,
	Folder VARCHAR2(256) NOT NULL,
	ScriptNumber SMALLINT NOT NULL,
	FileName VARCHAR2(512) NOT NULL,
	StartDate TIMESTAMP NOT NULL,
	CompleteDate TIMESTAMP NULL,
	AppliedBy VARCHAR2(128) NOT NULL,
	Status TINYINT NOT NULL,
	Output CLOB NULL
);

ALTER TABLE TABLE_NAME ADD CONSTRAINT PK_TABLE_NAME PRIMARY KEY (ChangeId);

CREATE INDEX IX_TABLE_NAME ON TABLE_NAME (Folder, ScriptNumber)