CREATE TABLE ChangeLog (
	ChangeId INT NOT NULL AUTO_INCREMENT,
	Folder VARCHAR2(256) NOT NULL,
	ScriptNumber SMALLINT NOT NULL,
	FileName VARCHAR2(512) NOT NULL,
	StartDate TIMESTAMP NOT NULL,
	CompleteDate TIMESTAMP NULL,
	AppliedBy VARCHAR2(128) NOT NULL,
	Status TINYINT NOT NULL,
	Output CLOB NULL
);

ALTER TABLE ChangeLog ADD CONSTRAINT PK_ChangeLog PRIMARY KEY (ChangeId);

CREATE INDEX IX_ChangeLog ON ChangeLog (Folder, ScriptNumber)