CREATE TABLE ChangeLog (
	ChangeId INT NOT NULL AUTO_INCREMENT,
	Folder VARCHAR(256) NOT NULL,
	ScriptNumber SMALLINT NOT NULL,
	FileName VARCHAR(512) NOT NULL,
	StartDate DATETIME NOT NULL,
	CompleteDate DATETIME NULL,
	AppliedBy VARCHAR(128) NOT NULL,
	Status TINYINT NOT NULL,
	Output TEXT NULL
);

ALTER TABLE ChangeLog ADD CONSTRAINT PK_ChangeLog PRIMARY KEY (ChangeId);

ALTER TABLE ChangeLog ADD UNIQUE INDEX(Folder, ScriptNumber);